# These are supported funding model platforms
# Help us fund for our first domain and buy us a coffee

github: [@d3vobed}
gumroad domain donations: [https://d3vp1.gumroad.com/l/cyb3r]
buy me a coffee: [https://www.buymeacoffee.com/everythingcyb3r]
